apiVersion: v1
kind: Pod
metadata:
  labels:
    app: animated-pancake
  name: animated-pancake
  namespace: pancake
spec:
  volumes:
    - name: pancake-pv-storage
      persistentVolumeClaim:
        claimName: pancake-pv-claim
  containers:
  - image: animated-pancake:1.0
    imagePullPolicy: Never
    name: animated-pancake
    volumeMounts:
      - mountPath: "/usr/share/pancake-data"
        name: pancake-pv-storage
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: animated-pancake
  name: animated-pancake
spec:
  ports:
  - port: 6543
    protocol: TCP
    targetPort: 6543
  selector:
    app: animated-pancake
  type: LoadBalancer
status:
  loadBalancer: {}